### ISSUE TITLE
Theme not working with this directive.

### ISSUE THREAD

**Issue by durga-telsiz** [fusioncharts/angularjs-fusioncharts#5] opened 2015-02-27 19:43 UTC
Team,

Theme parameter has no impact in chart rendering. Try the following code with bellow data object
 < ...   fc-chart fc-chart-type="MSLine" fc-data="sampleData" width="100%" height="100%"/     ....>
$scope.sampleData = {
        "chart": {
          "caption": "Store footfall - Last quarter",
          "subCaption": "Top 5 stores",
          "xAxisName": "Quarter",
          "yAxisName": "No of visitors",
          "divlineDashed": "0",
          "numMinorDivLines" : "4",
          "theme" : "ocean"
        },
        "categories": [
          {
            "category": [
              {
                "label": "Los Angeles Topanga"
              },
              {
                "label": "Bakersfield Central"
              },
              {
                "label": "Garden Groove harbour"
              },
              {
                "label": "Crompton-Rancho Dom"
              },
              {
                "label": "Daly City Serramonte"
              }
            ]
          }
        ],
        "dataset": [
          {
            "seriesname": "Total footfalls",
            "data": [
              {
                "value": "1960000"
              },
              {
                "value": "1110000"
              },
              {
                "value": "609000"
              },
              {
                "value": "560000"
              },
              {
                "value": "470000"
              }
            ]
          },
          {
            "seriesname": "No of Transactions",
            "data": [
              {
                "value": "126000"
              },
              {
                "value": "92140"
              },
              {
                "value": "36000"
              },
              {
                "value": "46000"
              },
              {
                "value": "83000"
              }
            ]
          }
        ]
      };

**Comment by ayanonly1** [comment] 2015-05-15 12:48
Check http://jsfiddle.net/ayanonly1/j3ttakmo/. You have to include the theme file in the page.

**Comment by jordidebarcelona** [comment] 2015-06-03 15:20
Are you sure the theme is working? If I remove the "theme":"fint" line of the sample I'm getting the same output.

I'm also experiencing strange behaviour when using themes and the fusionchart-angular plug-in. Strange things I'm getting are:
- When using data in XML format everything works fine.
- When using data in JSON format:
  - In firefox, the chart is displyed ignoring the theme
  - In Chrome, no chart is displayed and the "No data to display message" is shown

**Comment by ayanonly1** [comment] 2015-06-16 06:55
Hi @jordidebarcelona ,

There was an issue with the HTTPS link of the theme file. Please check the sample now. 
The issue in Chrome is a known issue in FusinCharts. And there is nothing related to the Angular plugin. We are working on this,. Will be fixed very soon.

**Comment by jordidebarcelona** [comment] 2015-06-21 11:53
I checked your sample and it Works.

But then, why is this http://jsfiddle.net/jordidebarcelona/a9pkjfcj/ failing? It displays 2 charts, one specifing a theme and the other one not.
The theme is never applied, and in Chrome the chart with a theme is not displayed.

I reported this to FusionCharts technical support. They are looking at it.

**Comment by ayanonly1** [comment] 2015-08-11 06:49
Hi @jordidebarcelona ,

Sorry! for the delayed reply.
This is a known issue in FusionCharts library. We are working on it. Till then, you can solve the issue by removing the extra ":" in the "seriesName" attribute for the charts where you are using theme.

**Comment by inothings** [comment] 2016-01-12 12:33
Hello, 

I met the same issue in chrome: saw "No data to display message" is shown; it works well in firefox...

I tried to download the latest version 3.10.0, but it does not help.
Has this issue resolved and included in latest version? Any workaround?

Thanks!

**Comment by ayanonly1** [comment] 2016-01-14 14:31
Hi @inothings,

Thanks for your reply. 
No, the issue is not fixed in FusionCharts v3.10.  But if you share a fiddle sample, we will check if there is any workaround.

**Comment by inothings** [comment] 2016-01-15 08:18
Thanks Ayan for confirm! We decided to disable this configuration till new version FusionCharts includes the fixing.

Thanks again!

**Comment by ashok1994** [comment] 2018-09-25 12:36
Forked @jordidebarcelona  http://jsfiddle.net/jordidebarcelona/a9pkjfcj/
Its working with latest update, 
http://jsfiddle.net/ashok1994/8o23xqpd/

Closing for now, please feel free to reopen if any problem persist

**Closed as completed by ashok1994** 2018-09-25 12:36 UTC
